### ISSUE TITLE
Can you please add additional layouts like Dvorak, Colemak ?

### ISSUE THREAD

**Issue by whoibrar** [kualta/Hemi#1]
This is really cool tool, can you please add support for other layouts as well. 
Thank you!

**Comment by kualta** [comment]
The right side of the dvorak keyboard consists only of consonants, wouldn't be possible to generate a word dictionary for that. Colemak is doable I think, I'll look into it.

**Comment by whoibrar** [comment]
Yeah, I use Colemak. It would be great to have that. Thank you so much for considering this.

**Comment by kualta** [comment]
implemented in 3.1

**Comment by whoibrar** [comment]
Thankyou so much for implementing this. Much appreciated 💖
