### ISSUE TITLE
Target word is not shown until a key is pressed?

### ISSUE THREAD

**Issue by rparrett** [kualta/hemi#6]
I am seeing the following in chrome on macos when first loading up the app

![image](https://github.com/user-attachments/assets/1766f5b5-028e-40f8-a9b1-33041b0f18ad)

If I press a key, a word will show up that I am presumably supposed to type

<img width="811" alt="image" src="https://github.com/user-attachments/assets/3e35a8ee-0708-4ab2-85c3-2dff4c32c23f">

From then on, things seem to work as expected, but I have to delete that first character so I can type the word correctly.

**Comment by kualta** [comment]
thank you @rparrett! this should be fixed now
